apiVersion: v1
kind: Service
metadata:
  name: springboot-api-svc
spec:
  type: LoadBalancer            # gives you a public IP
  selector:
    app: springboot-api
  ports:
    - port: 80
      targetPort: 8080
