name: Build & Deploy to AKS

on:
  push:
    branches: [ main ]

env:
  REGISTRY: fdxpocacr.azurecr.io
  IMAGE_NAME: springboot-demo

permissions:
  id-token: write    # For OIDC authentication
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 0. Checkout source code
      - uses: actions/checkout@v4

      # 1. Set up Java and Gradle cache
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v3

      # 2. Run unit tests
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      # 3. Azure login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Optional: Validate login
      - name: Verify Azure Login
        run: az account show

      # 4. Login to Azure Container Registry
      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      # 5. Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} -t $REGISTRY/$IMAGE_NAME:latest .
          docker push  $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push  $REGISTRY/$IMAGE_NAME:latest
#          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
#          docker push    $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      # 6. Set AKS kubectl context
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: fdx-poc-az-aks-rg
          cluster-name: fdxAksCluster

      # 7. Deploy to AKS with manifest substitution
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            $REGISTRY/$IMAGE_NAME:${{ github.sha }}
